kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - go build
  when:
    branch:
    - master
    event:
    - pull_request

- name: test
  image: golang:1.13
  commands:
  - go test -v
