kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.13
  commands:
  - go build

- name: test
  image: golang:1.13
  commands:
  - go test -v
  depends_on:
  - build
  
- name: hello
  image: golang:1.13
  commands:
  - echo hello
  depends_on:
  - build

- name: publish
  image: plugins/docker
  settings:
    repo: foo/bar
    tags: latest
    dry_run: true
  depends_on:
  - hello
  - test

