kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.13
  commands:
  - go build

- name: test
  image: golang:1.13
  commands:
  - go test -v

- name: publish
  image: plugins/docker
  settings:
    repo: foo/bar
    tags: latest
    dry_run: true
  when:
    branch:
    - master
    event:
    - push


---
kind: pipeline
type: docker
name: test

steps:
- name: build
  image: golang:1.13
  commands:
  - go build

depends_on:
- build
